// Community decks by @MissCappaLorina (curiosa.io), included with permission.
import type { DeckList } from '../engine/decks'
// each deck's curiosa sideboard is its in-game collection (some are empty)
import communityCollections from './communityCollections.json'

const communityDeckList: DeckList[] = [
  {
    name: "Interrogator a Spasso con lo Squalo",
    avatar: "Interrogator",
    atlas: {
      "Autumn River": 1,
      "Floodplain": 3,
      "Island Leviathan": 1,
      "Maelström": 1,
      "Spring River": 1,
      "Tadpole Pool": 1,
      "Undertow": 3,
      "Babbling Brook": 3,
      "Kelp Cavern": 2,
      "Troll Bridge": 3,
      "Croaking Swamp": 4,
      "Mismanaged Mortuary": 2,
      "River Rapids": 2,
      "Thin Ice": 3,
    },
    spellbook: {
      "Giant Shark": 3,
      "Great Old One": 1,
      "Lord of Unland": 1,
      "Polar Bears": 4,
      "Polar Explorers": 2,
      "Drown": 2,
      "Pollimorph": 2,
      "Riptide": 4,
      "Stormy Seas": 1,
      "Flood": 2,
      "Coy Nixie": 3,
      "Lugbog Cat": 3,
      "Nelly Longarms": 1,
      "Snowball": 2,
      "The Great Drowning of Men": 1,
      "Swap": 2,
      "Abaddon Succubus": 2,
      "Call of the Sea": 2,
      "Gift of the Frog": 4,
      "Into the Abyss": 2,
      "Lacuna Entity": 2,
      "Nommo Monitor": 3,
      "Orm Infestor": 2,
      "Overflow": 3,
      "Sewer Rats": 4,
      "Silver Bullet": 2,
    },
  },
  {
    name: "Terrharbinger - Torneo Covo del Nerd 16/07/2026",
    avatar: "Harbinger",
    atlas: {
      "Bedrock": 2,
      "Humble Village": 4,
      "Pillar of Zeiros": 1,
      "Rustic Village": 4,
      "Simple Village": 4,
      "Briar Patch": 3,
      "Common Village": 4,
      "Wizard's Den": 2,
      "Boulevard of Bones": 2,
      "Ghost Town": 3,
      "Mount Ussar Sanctuary": 1,
    },
    spellbook: {
      "Autumn Unicorn": 3,
      "Bosk Troll": 2,
      "House Arn Bannerman": 3,
      "King of the Realm": 1,
      "Land Surveyor": 2,
      "Pudge Butcher": 3,
      "Queen of Midland": 1,
      "Root Spider": 3,
      "Shield Maidens": 3,
      "Bury": 3,
      "Cave-In": 1,
      "Common Sense": 2,
      "Craterize": 2,
      "Earthquake": 2,
      "Rolling Boulder": 3,
      "Kettletop Leprechaun": 3,
      "Lady Iseult": 1,
      "Tithe": 1,
      "Croll Morlocks": 3,
      "Gargantula": 2,
      "Gift of the Wolf": 4,
      "Landmass": 3,
      "Lord of Greed": 2,
      "Malakhim": 2,
      "Smite": 2,
      "Toolbox": 3,
    },
  },
  {
    name: "Savior (Acqua-Terra)",
    avatar: "Savior",
    atlas: {
      "Bedrock": 1,
      "Autumn River": 2,
      "Iceberg": 1,
      "Spring River": 1,
      "Summer River": 1,
      "Aqueduct": 3,
      "Briar Patch": 1,
      "Common Village": 2,
      "Pebbled Paths": 1,
      "Valley of Delight": 2,
      "Haystack": 1,
      "Blessed Village": 4,
      "Blessed Well": 4,
      "Deep Sea": 3,
      "Fertile Earth": 3,
    },
    spellbook: {
      "Älvalinne Dryads": 4,
      "Bosk Troll": 1,
      "Land Surveyor": 4,
      "Mordric Druids": 2,
      "Wraetannis Titan": 1,
      "Cave-In": 1,
      "Craterize": 1,
      "Dispel": 2,
      "Brobdingnag Bullfrog": 3,
      "Captain Baldassare": 1,
      "Deep-Sea Mermaids": 3,
      "Porcupine Pufferfish": 2,
      "Tufted Turtles": 4,
      "Ice Lance": 4,
      "Shrink": 1,
      "Sleep": 1,
      "Stormy Seas": 1,
      "Field Laborers": 2,
      "Rescue": 1,
      "Ribble Boggart": 1,
      "Sir Ironside": 1,
      "Sly Fox": 3,
      "Spearmarshal": 1,
      "Sugarplum Pixies": 3,
      "Divine Lance": 1,
      "Doctor Demetrius": 1,
      "Faith Incarnate": 2,
      "Gift of the Frog": 4,
      "Gift of the Wolf": 1,
      "Holy Nova": 1,
      "Seraphim": 2,
    },
  },
  {
    name: "Terrharbinger (Earthbinger)",
    avatar: "Harbinger",
    atlas: {
      "Bedrock": 2,
      "Humble Village": 4,
      "Pillar of Zeiros": 1,
      "Rustic Village": 4,
      "Simple Village": 4,
      "Briar Patch": 3,
      "Common Village": 4,
      "Wizard's Den": 2,
      "Boulevard of Bones": 1,
      "Ghost Town": 3,
      "Mount Ussar Sanctuary": 1,
      "Troubled Town": 1,
    },
    spellbook: {
      "Autumn Unicorn": 3,
      "Bosk Troll": 2,
      "House Arn Bannerman": 3,
      "King of the Realm": 1,
      "Land Surveyor": 2,
      "Pudge Butcher": 3,
      "Queen of Midland": 1,
      "Root Spider": 3,
      "Shield Maidens": 3,
      "Bury": 3,
      "Cave-In": 1,
      "Common Sense": 2,
      "Craterize": 2,
      "Earthquake": 2,
      "Rolling Boulder": 3,
      "Kettletop Leprechaun": 3,
      "Lady Iseult": 1,
      "Tithe": 1,
      "Croll Morlocks": 3,
      "Gargantula": 2,
      "Gift of the Wolf": 4,
      "Landmass": 3,
      "Lord of Greed": 2,
      "Malakhim": 2,
      "Smite": 2,
      "Toolbox": 3,
    },
  },
  {
    name: "Reame Budget: Persecutor",
    avatar: "Persecutor",
    atlas: {
      "Steppe": 3,
      "Common Village": 1,
      "Funeral Pyre": 3,
      "River of Blood": 3,
      "Active Volcano": 2,
      "Autumn Bloom": 4,
      "Desert Bloom": 4,
      "Fertile Earth": 3,
      "Molten Maar": 3,
      "Open Grave": 4,
    },
    spellbook: {
      "Root Spider": 3,
      "Cave-In": 2,
      "Common Sense": 2,
      "Dispel": 1,
      "Cerberus in Chains": 1,
      "Hillock Basilisk": 3,
      "Infernal Legion": 2,
      "Vile Imp": 4,
      "Firebolts": 2,
      "Heat Ray": 1,
      "Mad Dash": 4,
      "Minor Explosion": 2,
      "Poison Nova": 3,
      "Firebreathing": 1,
      "Kettletop Leprechaun": 4,
      "Lava Flow": 3,
      "Barging Barghest": 3,
      "Begone!": 3,
      "Ignited": 2,
      "Màzuj Ifrit": 2,
      "Peacemaker Arbalest": 2,
      "Redmane Hyena": 3,
      "Slobbermaw": 3,
      "Smite": 4,
    },
  },
  {
    name: "Reame Budget: Persecutor di P999",
    avatar: "Persecutor",
    atlas: {
      "Rift Valley": 1,
      "Red Desert": 2,
      "Smokestacks of Gnaak": 1,
      "Steppe": 3,
      "Primordial Spring": 1,
      "Funeral Pyre": 1,
      "River of Blood": 2,
      "Active Volcano": 3,
      "Boulevard of Bones": 2,
      "Fertile Earth": 3,
      "Kor Crematory": 1,
      "Leadworks": 1,
      "Molten Maar": 1,
      "Open Grave": 4,
      "Plague Pits": 1,
      "Silent Hills": 2,
      "Vast Desert": 1,
    },
    spellbook: {
      "Pudge Butcher": 2,
      "Root Spider": 3,
      "Cave-In": 2,
      "Common Sense": 1,
      "Dispel": 1,
      "Earthquake": 1,
      "Cerberus in Chains": 1,
      "Colicky Dragonettes": 3,
      "Courtesan Thaïs": 1,
      "Hillock Basilisk": 2,
      "Infernal Legion": 1,
      "Quarrelsome Kobolds": 3,
      "Vile Imp": 4,
      "Disintegrate": 1,
      "Firebolts": 2,
      "Immolation": 1,
      "Poison Nova": 2,
      "Flaming Sword": 1,
      "Screaming Skull": 1,
      "Torshammar Trinket": 1,
      "Boudicca": 1,
      "Firebreathing": 1,
      "Lava Flow": 1,
      "Sword and Shield": 1,
      "Arjaro Exorcist": 2,
      "Begone!": 3,
      "Betrayal": 2,
      "Gargantula": 2,
      "Grigori Rasputin": 1,
      "Hotwheel": 1,
      "Lord of Greed": 1,
      "Màzuj Ifrit": 2,
      "Peacemaker Arbalest": 1,
      "Powerwish": 1,
      "Redmane Hyena": 3,
      "Searing Truth": 1,
      "Smite": 1,
      "Toolbox": 2,
    },
  },
  {
    name: "Under The Seavior",
    avatar: "Savior",
    atlas: {
      "Autumn River": 3,
      "Floodplain": 3,
      "Maelström": 1,
      "Spring River": 3,
      "Summer River": 3,
      "Tadpole Pool": 1,
      "Babbling Brook": 3,
      "Kelp Cavern": 2,
      "Troll Bridge": 3,
      "Croaking Swamp": 4,
      "Mismanaged Mortuary": 2,
      "River Rapids": 2,
    },
    spellbook: {
      "Anui Undine": 1,
      "Brobdingnag Bullfrog": 3,
      "Captain Baldassare": 1,
      "Deep-Sea Mermaids": 3,
      "Giant Shark": 3,
      "Lord of Unland": 1,
      "Porcupine Pufferfish": 4,
      "Tufted Turtles": 4,
      "Drown": 2,
      "Pollimorph": 2,
      "Riptide": 4,
      "Stormy Seas": 1,
      "Abundance": 2,
      "Flood": 3,
      "Mester Stoor Worm": 2,
      "Nelly Longarms": 1,
      "Snowball": 2,
      "Sugarplum Pixies": 3,
      "The Great Drowning of Men": 1,
      "Swap": 3,
      "Call of the Sea": 2,
      "Doctor Demetrius": 1,
      "Gift of the Frog": 3,
      "Into the Abyss": 2,
      "Overflow": 4,
      "Seraphim": 2,
    },
  },
  {
    name: "Ironclad Ironchad (Mono Aria)",
    avatar: "Ironclad",
    atlas: {
      "Cloud City": 1,
      "Dark Tower": 1,
      "Gothic Tower": 1,
      "Lone Tower": 1,
      "Observatory": 2,
      "Updraft Ridge": 3,
      "Bottomless Pit": 2,
      "Beacon": 3,
      "Lookout": 1,
      "Merlin's Tower": 1,
      "Perilous Bridge": 2,
      "Treetop Hideout": 4,
      "Fields of Phyxis": 3,
      "Bureau of Occult Control": 2,
      "Dark Alley": 3,
    },
    spellbook: {
      "Cloud Spirit": 4,
      "Daperyll Vampire": 3,
      "Grandmaster Wizard": 2,
      "Gyre Hippogriffs": 3,
      "Plumed Pegasus": 4,
      "Blink": 3,
      "Browse": 1,
      "Chaos Twister": 2,
      "Grapple Shot": 3,
      "Lightning Bolt": 3,
      "Whirling Blades": 3,
      "Arcane Barrage": 1,
      "Bailey": 3,
      "Cast into Exile": 2,
      "Magic Missiles": 3,
      "Tooth Faeries": 3,
      "Displace": 1,
      "Gibbous Nightgaunts": 3,
      "Gift of the Raven": 2,
      "Legion of Gall": 2,
      "Ophanim": 1,
      "Pith Imp": 4,
      "Renatus Trueblood": 2,
      "Sturmgeist": 2,
    },
  },
  {
    name: "(De)Ranged Elementalist",
    avatar: "Elementalist",
    atlas: {
      "Dark Tower": 1,
      "Gothic Tower": 1,
      "Lone Tower": 1,
      "Mountain Pass": 1,
      "Watchtower": 1,
      "Vantage Hills": 3,
      "Arid Desert": 2,
      "Red Desert": 1,
      "Remote Desert": 2,
      "Ruins": 3,
      "Mudflow": 3,
      "Funeral Pyre": 2,
      "Valley of Delight": 2,
      "Wizard's Den": 2,
      "River of Blood": 3,
      "Wuthering Heights": 2,
    },
    spellbook: {
      "Kite Archer": 3,
      "Midnight Rogue": 4,
      "Skirmishers of Mu": 3,
      "Sling Pixies": 3,
      "Blink": 3,
      "Belmotte Longbowmen": 3,
      "Bury": 1,
      "Colicky Dragonettes": 3,
      "Accursed Albatross": 2,
      "Poisonous Dagger": 3,
      "Fail-not Bow": 1,
      "Grim Guisarme": 2,
      "Queen Guinevere": 1,
      "Sherwood Huntress": 4,
      "Siege Giant": 2,
      "Sir Bors the Younger": 1,
      "Sly Fox": 3,
      "Whirlwind": 3,
      "Apply Alkahest": 1,
      "Displace": 2,
      "Gift of the Serpent": 3,
      "Lash": 2,
      "Searing Truth": 1,
      "Stygian Archers": 3,
      "Toolbox": 3,
    },
  },
  {
    name: "Acqua-Aria 3.1 (Gothic)",
    avatar: "Waveshaper",
    atlas: {
      "Dark Tower": 1,
      "Gothic Tower": 1,
      "Lone Tower": 1,
      "Observatory": 1,
      "Autumn River": 1,
      "Floodplain": 3,
      "Maelström": 1,
      "Spring River": 1,
      "Summer River": 1,
      "Tadpole Pool": 1,
      "Lighthouse": 3,
      "Kelp Cavern": 2,
      "Lookout": 1,
      "Troll Bridge": 3,
      "Algae Bloom": 2,
      "Mismanaged Mortuary": 2,
      "River Rapids": 2,
      "Stinging Kelp": 3,
    },
    spellbook: {
      "Lightning Bolt": 3,
      "Anui Undine": 2,
      "Coral-Reef Kelpie": 1,
      "Diluvian Kraken": 1,
      "Great Old One": 1,
      "Lord of Unland": 1,
      "Porcupine Pufferfish": 4,
      "Tide Naiads": 3,
      "Unland Eel": 1,
      "Drown": 3,
      "Pollimorph": 1,
      "Riptide": 3,
      "Wrath of the Sea": 1,
      "Flood": 2,
      "Mariner's Curse": 1,
      "Sunken Treasure": 3,
      "Lake Afanc": 1,
      "Mester Stoor Worm": 2,
      "Nelly Longarms": 1,
      "Sir Pelleas": 1,
      "Snowball": 1,
      "The Great Drowning of Men": 1,
      "Swap": 1,
      "Call of the Sea": 2,
      "Hearkening Kraken": 2,
      "Hyperparasite": 1,
      "Into the Abyss": 2,
      "Lacuna Entity": 2,
      "Nommo Monitor": 3,
      "Orm Infestor": 2,
      "Overflow": 4,
      "Putrid Presence": 1,
      "Silver Bullet": 2,
    },
  },
  {
    name: "Sorcerer Frog (Acqua - Fuoco)",
    avatar: "Sorcerer",
    atlas: {
      "Oasis": 3,
      "Forge": 4,
      "Funeral Pyre": 1,
      "Poisoned Well": 2,
      "Troll Bridge": 3,
      "Active Volcano": 3,
      "Algae Bloom": 4,
      "Croaking Swamp": 4,
      "Deep Sea": 3,
      "Desert Bloom": 3,
    },
    spellbook: {
      "Quarrelsome Kobolds": 3,
      "Vile Imp": 4,
      "Disintegrate": 2,
      "Minor Explosion": 1,
      "Poison Nova": 1,
      "Adept Illusionist": 2,
      "Fey Changeling": 1,
      "Swan Maidens": 3,
      "Pollimorph": 1,
      "Abundance": 2,
      "Coy Nixie": 3,
      "Lugbog Cat": 3,
      "Shatter Strike": 1,
      "Sir Agravaine": 1,
      "Swap": 2,
      "Abaddon Succubus": 1,
      "Abyssal Assault": 2,
      "Barging Barghest": 2,
      "Blaze of Glory": 1,
      "Estranged Loner": 2,
      "Failed Mutation": 3,
      "Gift of the Frog": 4,
      "Hand of Glory": 3,
      "Lord of Lies": 2,
      "Mimic": 1,
      "Orm Infestor": 2,
      "Slimy Mutants": 4,
      "Slobbermaw": 3,
    },
  },
  {
    name: "Seer Dune (Mono fuoco) - Casual",
    avatar: "Seer",
    atlas: {
      "Arid Desert": 4,
      "Red Desert": 4,
      "Remote Desert": 4,
      "Shifting Sands": 3,
      "Vesuvius": 1,
      "Crossroads": 1,
      "Hamlet": 4,
      "Accursed Desert": 4,
      "Ghost Town": 1,
      "Vast Desert": 4,
    },
    spellbook: {
      "Petrosian Cavalry": 4,
      "Pit Vipers": 2,
      "Rimland Nomads": 4,
      "Sacred Scarabs": 2,
      "Sand Worm": 4,
      "Sirocco Scorpions": 2,
      "Blaze": 1,
      "Firebolts": 1,
      "Heat Ray": 3,
      "Leap Attack": 1,
      "Mad Dash": 4,
      "Minor Explosion": 1,
      "Poison Nova": 1,
      "Harassing Ruffians": 2,
      "Reckless Squire": 2,
      "Redbreast Robin": 2,
      "Saracen Raiders": 2,
      "Saracen Scout": 2,
      "Shatter Strike": 2,
      "Vikings": 2,
      "Angry Mob": 4,
      "Bodach Bogeyman": 1,
      "Corpse Explosion": 2,
      "Khamaseen Mummy": 3,
      "Locusts of Illyria": 1,
      "Martyrs of Tomorrow": 2,
      "Satanic Panic": 1,
      "Wild Fanatic": 2,
    },
  },
  {
    name: "SPOOKY SCARY SKELETON v2",
    avatar: "Necromancer",
    atlas: {
      "Ruins": 3,
      "Steppe": 3,
      "Windmill": 3,
      "Annual Fair": 2,
      "Valley of Delight": 2,
      "Active Volcano": 3,
      "Boulevard of Bones": 1,
      "Den of Evil": 4,
      "Desert Bloom": 3,
      "Fertile Earth": 1,
      "Mountain Peaks": 1,
      "Sold-out Cemetery": 1,
      "Twilight Bloom": 3,
    },
    spellbook: {
      "Blink": 4,
      "Bury": 1,
      "Heat Ray": 3,
      "Pact with the Devil": 1,
      "Boudicca": 1,
      "Horn of Caerleon": 2,
      "Arcade of Bones": 2,
      "Army of the Dead": 1,
      "Barrow Wight": 3,
      "Bone Jumble": 3,
      "Bone Spear": 2,
      "Carrionette": 1,
      "Corpse Catapult": 2,
      "Death Knight": 3,
      "Exhume": 3,
      "Flaming Skull": 2,
      "Gift of the Serpent": 2,
      "Kiss of Death": 3,
      "Necronomiconcert": 2,
      "Noisome Twosome": 4,
      "Panpipes of Pnom": 2,
      "Raise Militia": 4,
      "Undead Ambush": 3,
      "Witching Hour": 3,
      "Young Master Damion": 1,
      "Zombie Bruiser": 2,
    },
  },
  {
    name: "Interrogator (Aria/Fuoco) V2",
    avatar: "Interrogator",
    atlas: {
      "Dark Tower": 3,
      "Gothic Tower": 3,
      "Lone Tower": 3,
      "Observatory": 1,
      "Ruins": 3,
      "Beacon": 1,
      "Forge": 4,
      "Funeral Pyre": 1,
      "Poisoned Well": 3,
      "River of Blood": 1,
      "Active Volcano": 3,
      "Desert Bloom": 1,
      "Spore Spouts": 2,
      "Twilight Bloom": 1,
    },
    spellbook: {
      "Grim Reaper": 1,
      "Phantom Steed": 3,
      "Phase Assassin": 1,
      "Roaming Monster": 3,
      "Spectral Stalker": 4,
      "Blink": 2,
      "Browse": 1,
      "Chaos Twister": 2,
      "Disenchant": 1,
      "Grapple Shot": 4,
      "Lightning Bolt": 3,
      "Teleport": 3,
      "Whirling Blades": 1,
      "Summoning Sphere": 3,
      "Spin Attack": 2,
      "Arcane Barrage": 1,
      "Brother Knight": 2,
      "Feast for Crows": 1,
      "Redcap Powries": 3,
      "Sir Balin": 1,
      "Sir Lamorak": 1,
      "Sir Pellinore": 1,
      "Barging Barghest": 2,
      "Blaze of Glory": 1,
      "Corruptor Freak": 1,
      "Displace": 2,
      "Gibbous Nightgaunts": 3,
      "Legion of Gall": 1,
      "Lord of Fear": 2,
      "Ophanim": 2,
      "Sturmgeist": 2,
    },
  },
  {
    name: "Savior - Beast Mode",
    avatar: "Savior",
    atlas: {
      "Aqueduct": 3,
      "Lighthouse": 3,
      "Oasis": 3,
      "Ruins": 3,
      "Steppe": 3,
      "Windmill": 3,
      "Annual Fair": 1,
      "Pond": 4,
      "Valley of Delight": 2,
      "Varmint Warrens": 2,
      "Desert Bloom": 2,
      "Twilight Bloom": 1,
    },
    spellbook: {
      "Älvalinne Dryads": 4,
      "Land Surveyor": 2,
      "Squirming Mass": 1,
      "Assorted Animals": 1,
      "Cave-In": 1,
      "Common Sense": 4,
      "Craterize": 1,
      "Dispel": 1,
      "Hillock Basilisk": 2,
      "Pit Vipers": 4,
      "Sirocco Scorpions": 4,
      "Spin Attack": 4,
      "Brobdingnag Bullfrog": 3,
      "Captain Baldassare": 1,
      "Porcupine Pufferfish": 2,
      "Tufted Turtles": 4,
      "Stormy Seas": 1,
      "Lugbog Cat": 3,
      "Rescue": 1,
      "Sir Ironside": 1,
      "Sly Fox": 3,
      "War Horse": 2,
      "Wolpertinger": 1,
      "Doctor Demetrius": 1,
      "Faith Incarnate": 2,
      "Holy Nova": 1,
      "Plague Rat": 4,
      "Sacred Stag": 1,
    },
  },
  {
    name: "Elementalist Spellcasters",
    avatar: "Elementalist",
    atlas: {
      "Gothic Tower": 1,
      "Gnome Hollows": 2,
      "Aqueduct": 3,
      "Lighthouse": 3,
      "Oasis": 3,
      "Ruins": 3,
      "Steppe": 3,
      "Windmill": 3,
      "Annual Fair": 1,
      "Merlin's Tower": 1,
      "Valley of Delight": 2,
      "Active Volcano": 3,
      "Desert Bloom": 1,
      "Thin Ice": 1,
    },
    spellbook: {
      "Apprentice Wizard": 4,
      "Grandmaster Wizard": 1,
      "Occult Ritual": 1,
      "Border Militia": 4,
      "Common Sense": 3,
      "Disintegrate": 1,
      "Firebolts": 4,
      "Heat Ray": 2,
      "Major Explosion": 2,
      "Minor Explosion": 1,
      "Pact with the Devil": 1,
      "Poison Nova": 1,
      "Adept Illusionist": 2,
      "Pollimorph": 2,
      "Shrink": 3,
      "Sleep": 3,
      "Boudicca": 1,
      "Guards!": 2,
      "Magic Missiles": 4,
      "Sisters of Avalon": 2,
      "Tactical Move": 2,
      "Ghostfire": 3,
      "Gift of the Serpent": 1,
      "Novice Necromancer": 2,
      "Raise Militia": 3,
      "Skeleton Mage": 3,
      "Toolbox": 3,
    },
  },
  {
    name: "Interrogator (Aria/Fuoco)",
    avatar: "Interrogator",
    atlas: {
      "Dark Tower": 3,
      "Gothic Tower": 3,
      "Lone Tower": 3,
      "Observatory": 2,
      "Arid Desert": 2,
      "Red Desert": 3,
      "Remote Desert": 3,
      "Vesuvius": 1,
      "Ruins": 3,
      "Forge": 1,
      "Funeral Pyre": 1,
      "River of Blood": 1,
      "Darkest Dungeon": 1,
      "Desert Bloom": 1,
      "Mountain Peaks": 1,
      "Twilight Bloom": 1,
    },
    spellbook: {
      "Grim Reaper": 1,
      "Hounds of Ondaros": 1,
      "Phantom Steed": 1,
      "Roaming Monster": 3,
      "Spectral Stalker": 3,
      "Chaos Twister": 2,
      "Disenchant": 1,
      "Grapple Shot": 3,
      "Lightning Bolt": 3,
      "Teleport": 4,
      "Waypoint Portal": 2,
      "Summoning Sphere": 3,
      "Quarrelsome Kobolds": 3,
      "Sirocco Scorpions": 3,
      "Spin Attack": 3,
      "Monstrous Lion": 1,
      "Redcap Powries": 3,
      "Saracen Raiders": 3,
      "Saracen Scout": 2,
      "Sir Balin": 1,
      "Sir Lamorak": 1,
      "Sir Pellinore": 1,
      "War Horse": 2,
      "Blaze of Glory": 1,
      "Bodach Bogeyman": 1,
      "Gibbous Nightgaunts": 3,
      "Locusts of Illyria": 1,
      "Lord of Destruction": 2,
      "Sturmgeist": 2,
    },
  },
  {
    name: "Animist Jamboree",
    avatar: "Animist",
    atlas: {
      "Aqueduct": 3,
      "Lighthouse": 3,
      "Oasis": 3,
      "Pristine Paradise": 1,
      "Ruins": 3,
      "Steppe": 3,
      "Windmill": 3,
      "Annual Fair": 1,
      "Valley of Delight": 2,
      "Active Volcano": 3,
      "Deep Sea": 1,
      "Desert Bloom": 1,
      "Fertile Earth": 2,
      "Mountain Peaks": 1,
    },
    spellbook: {
      "Blink": 1,
      "Chaos Twister": 1,
      "Disenchant": 2,
      "Evil Presence": 3,
      "Border Militia": 4,
      "Common Sense": 3,
      "Disintegrate": 1,
      "Fireball": 1,
      "Firebolts": 1,
      "Heat Ray": 1,
      "Mad Dash": 1,
      "Poison Nova": 2,
      "Pollimorph": 2,
      "Shrink": 3,
      "Sleep": 1,
      "Ball Lightning": 1,
      "Grievous Insult": 1,
      "Guards!": 2,
      "Power of Flight": 1,
      "Snowball": 1,
      "Vanishment": 2,
      "Corpse Explosion": 1,
      "Ghostfire": 4,
      "Gift of the Frog": 1,
      "Gift of the Raven": 1,
      "Gift of the Serpent": 2,
      "Gift of the Wolf": 1,
      "Murder of Crows": 3,
      "Raise Militia": 3,
      "Return to Nature": 2,
      "Searing Truth": 1,
      "Smite": 1,
      "Toolbox": 3,
      "Wiccan Tools": 2,
    },
  },
  {
    name: "SPOOKY SCARY SKELETON",
    avatar: "Necromancer",
    atlas: {
      "Ruins": 3,
      "Steppe": 3,
      "Windmill": 3,
      "Annual Fair": 2,
      "Valley of Delight": 2,
      "Active Volcano": 3,
      "Boulevard of Bones": 1,
      "Den of Evil": 4,
      "Desert Bloom": 3,
      "Fertile Earth": 1,
      "Mountain Peaks": 1,
      "Sold-out Cemetery": 1,
      "Twilight Bloom": 3,
    },
    spellbook: {
      "Bury": 1,
      "Firebolts": 1,
      "Heat Ray": 4,
      "Minor Explosion": 1,
      "Pact with the Devil": 1,
      "Horn of Caerleon": 2,
      "Arcade of Bones": 2,
      "Barrow Wight": 4,
      "Bleeding Skull": 2,
      "Bone Jumble": 3,
      "Bone Spear": 3,
      "Carrionette": 1,
      "Corpse Catapult": 2,
      "Death Knight": 2,
      "Exhume": 3,
      "Hand of Glory": 2,
      "Kiss of Death": 3,
      "Necronomiconcert": 2,
      "Noisome Twosome": 3,
      "Panpipes of Pnom": 2,
      "Raise Militia": 4,
      "Searing Truth": 2,
      "Skeleton Mage": 3,
      "Undead Ambush": 3,
      "Witching Hour": 2,
      "Young Master Damion": 1,
      "Zombie Bruiser": 1,
    },
  },
  {
    name: "Acqua 3.0 (Gothic)",
    avatar: "Waveshaper",
    atlas: {
      "Dark Tower": 1,
      "Gothic Tower": 1,
      "Lone Tower": 2,
      "Observatory": 1,
      "Autumn River": 4,
      "Floodplain": 2,
      "Maelström": 1,
      "Spring River": 3,
      "Summer River": 2,
      "Tadpole Pool": 1,
      "Undertow": 1,
      "Lighthouse": 3,
      "Troll Bridge": 2,
      "Algae Bloom": 2,
      "Stinging Kelp": 4,
    },
    spellbook: {
      "Lightning Bolt": 3,
      "Accursed Albatross": 1,
      "Anui Undine": 2,
      "Brobdingnag Bullfrog": 2,
      "Captain Baldassare": 1,
      "Diluvian Kraken": 1,
      "Great Old One": 1,
      "Lord of Unland": 1,
      "Pirate Ship": 2,
      "Porcupine Pufferfish": 4,
      "Seirawan Hydra": 1,
      "Tide Naiads": 3,
      "Drown": 3,
      "Ice Lance": 1,
      "Marine Voyage": 1,
      "Riptide": 2,
      "Sleep": 1,
      "Stormy Seas": 1,
      "Wrath of the Sea": 1,
      "Flood": 1,
      "Mariner's Curse": 1,
      "Sunken Treasure": 2,
      "Lugbog Cat": 3,
      "Magic Missiles": 1,
      "Mester Stoor Worm": 1,
      "Muirid Fomorians": 1,
      "Nelly Longarms": 1,
      "Sir Pelleas": 1,
      "Snowball": 1,
      "The Great Drowning of Men": 1,
      "Swap": 3,
      "Call of the Sea": 1,
      "Hearkening Kraken": 2,
      "Into the Abyss": 1,
      "Lacuna Entity": 1,
      "Overflow": 4,
      "Regurgitator": 1,
      "Sewer Rats": 1,
    },
  },
]

// Attach each deck's collection (its curiosa sideboard), matched by name. Decks
// whose sideboard is empty simply have no collection.
const communityCollectionMap = communityCollections as Record<string, Record<string, number>>
export const communityDecks: DeckList[] = communityDeckList.map((d) => {
  const c = communityCollectionMap[d.name]
  return c && Object.keys(c).length ? { ...d, collection: c } : d
})
