// Regenerates packages/shared/src/cards/scripts/gen/index.ts — one `import './x'` per script module
// in that folder. Each module self-registers its cards (registerScript side effect) on import, so the
// index just needs to import every module exactly once. Import ORDER is irrelevant: a guard test
// (card-index.test.ts) asserts no card name is registered by two modules, so nothing depends on "later
// wins". Run: `npm run gen:card-index`. A drift test keeps the committed file in sync in CI.
//
// This is the enabler for the one-file-per-card refactor: split a card out of an mN batch file into its
// own `gen/<slug>.ts`, rerun this, and it auto-registers — no hand-editing of the index.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

export const GEN_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'packages', 'shared', 'src', 'cards', 'scripts', 'gen')

/** the module basenames (no extension) that self-register cards — every `.ts` in `dir` except the
 *  index itself and pure helpers with no `registerScript` call (util.ts). Sorted for a stable diff. */
export function scriptModules(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
    .filter((f) => readFileSync(join(dir, f), 'utf8').includes('registerScript('))
    .map((f) => f.replace(/\.ts$/, ''))
    .sort((a, b) => a.localeCompare(b, 'en'))
}

/** the exact text the committed gen/index.ts must contain. */
export function renderIndex(dir: string): string {
  const header =
    '// AUTO-GENERATED by `npm run gen:card-index` — DO NOT EDIT BY HAND.\n' +
    '// One import per script module here; each self-registers its cards on import. Order is irrelevant\n' +
    '// (card-index.test.ts asserts no card is registered twice). To add a card, drop a new file and rerun.\n'
  return header + scriptModules(dir).map((m) => `import './${m}'`).join('\n') + '\n'
}

// run as a script (not when imported by the test)
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = renderIndex(GEN_DIR)
  writeFileSync(join(GEN_DIR, 'index.ts'), out)
  console.log(`wrote gen/index.ts (${scriptModules(GEN_DIR).length} modules)`)
}
